#################################################
# ATG Modules                                   #
#################################################

ATG_MODULES = [
  DAS,
  DAS_RESOURCES,
  DCS,
  DCS_RESOURCES,
  DPS,
  DPS_RESOURCES,
  PubBase,
  DSS,
  DSS_RESOURCES,
  SB_BL,
  SB_SSB,
  CRS_STORE_ESTORE,
  CRS_STORE_ESTORE_INTERNATIONAL,
  DAF_SEARCH_BASE, 
  DAF_SEARCH_INDEX,
  DAF_SEARCH_LIVEINDEX,
  DAF_SEARCH_ROUTING, 
  CRS_STORE_ESTORE,
  DAF_SEARCH_COMMON,
  DAF_SEARCH_QUERY,
  CRS_SEARCH_QUERY,
  SERVICE_FRAMEWORK
  ]

#################################################
# External Modules                              #
#################################################

EXTERNALS_MODULES = [
  EZMORPH,
  OAUTH,
  JSON_SF_NET,
  USER_VOICE,
  SERVLETAPI,
  JUNIT,
  MOCKITO,
  DOZER,
  COMMONS_BEANUTILS,
  COMMIDEA_BEANS,
  COMMIDEA_CLIENT,
  COMMONS_COLLECTIONS,
  JBOSS_JAVAEE,
  SLF4J,
  LOG4J,
  COMMONS_LANG,
  COMMONS_IO,
  POWERMOCK,
  COMMONS_COLLECTIONS,
  HIBERNATE_VALIDATION,
  WMQ,
  JSR303_API,
  SERVLETAPI,
  AXIS2,
  MARKUP,
  FINDBUG,
  GUAVA,
  JSCH,
  DWR,
  JSON_SIMPLE,
  JBOSS_SPI,
  SERVLET_JSP,
  BV_SEO,
  KF_SERVICES_COMUNICATION,
  KF_SERVICES_CUSTOMER,
  KF_SERVICES_TAX,
  KF_SERVICES_SELLING_CONTENT,
  KF_SERVICE_FULFILMENT_SOURCE,
  KF_SERVICE_INVOICE,
  KF_SERVICES_LOCATION,
KF_SERVICES_COMUNICATION,
KF_SERVICE_FULFILMENT_SOURCE,
KF_SERVICES_CARRIER_BOOKING
  ]

#################################################
# Kingfisher Modules                            #
#################################################

KF_MODULES = [
  COMMON_VALIDATION,
  COMMON_API,
  COMMON_BASE,
  COMMON_MESSAGING
 ]
